server:
  port: 28100
  undertow:
    io-threads: 16
    worker-threads: 256
    buffer-size: 1024
    direct-buffers: true
  connection-timeout: 3000

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://172.16.20.205:8761/eureka}
#      defaultZone: ${EUREKA_URI:http://172.16.20.191:8787/eureka}
  instance:
    preferIpAddress: true
#    statusPageUrlPath: ${eureka.hostname}/info
#    healthCheckUrlPath: ${eureka.hostname}/health
    health-check-url:
      enabled: true

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000

spring:
  application:
    name: mock-trading-system
  profiles:
    include: redis-test,postgre-test,kafka-test
logging:
  level:
    com:
      mouzhiapp:
        stock_market:
          mapper: debug
          mapper205: debug
#自定义参数
