server:
  port: 28090
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://172.16.63.34:8761/eureka}
  instance:
    preferIpAddress: true
#    statusPageUrlPath: ${eureka.hostname}/info
#    healthCheckUrlPath: ${eureka.hostname}/health
    health-check-url:
      enabled: true
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds:  5000

spring:
  application:
    name: xiaoxin
  profiles:
    include: postgre-aliyun,redis-aliyun
