#kafka相关配置
spring.kafka.bootstrap-servers: 47.96.103.74:9092
#设置一个默认组
spring.kafka.consumer.group-id: springboot-group1
#key-value序列化反序列化
spring.kafka.consumer.key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer: org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.batch-size: 65536
spring.kafka.producer.buffer-memory: 524288