server:
  port: 8773
spring:
  application:
    name: news
  profiles:
    include: postgre-aliyun , redis-aliyun ,kafka-aliyun
logging:
  level:
    com:
      mzkj:
        news:
          mapper: error