eureka.client.serviceUrl.defaultZone: http://172.16.20.205:8761/eureka

server.port: 8774

spring.application.name: user-mock
spring.profiles.include: postgre-test , redis-test

logging.level.com.mzkj.usermock: info

feign.client.config.feignName.connectTimeout: 5000
feign.client.config.feignName.readTimeout: 5000

