eureka.client.serviceUrl.defaultZone: ${EUREKA_URI:http://172.16.63.34:8761/eureka}
#eureka.client.serviceUrl.defaultZone: http://172.16.20.205:8761/eureka

server.port: 8774

spring.application.name: user-mock
spring.profiles.include: postgre-aliyun , redis-aliyun

feign.client.config.feignName.connectTimeout: 5000
feign.client.config.feignName.readTimeout: 5000

logging.level.com.mzkj.news.mapper: info
